services:
  backend:
    stdin_open: true
    tty: true
    build:
      context: ./backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app

  frontend:
    stdin_open: true
    tty: true
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/app:/app
